# Generated by Django 5.2.1 on 2025-11-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionimpresora',
            options={'verbose_name': 'Configuración de Impresora', 'verbose_name_plural': 'Configuraciones de Impresoras'},
        ),
        migrations.AddField(
            model_name='configuracionimpresora',
            name='alto_etiqueta',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracionimpresora',
            name='ancho_etiqueta',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='configuracionimpresora',
            name='densidad',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
